### ISSUE TITLE
Where to set or get cookies?

### ISSUE THREAD

**Issue by omar2205** [icflorescu/trpc-sveltekit#10]

**Comment by lkj4** [comment]
I presume you still do this in `hooks.ts`, https://github.com/icflorescu/trpc-sveltekit/pull/8 enables custom logic in `hooks.ts`

**Comment by omar2205** [comment]
I was asking inside a mutation, for example, or checking for an auth cookie inside mutations.

**Comment by ambiguous48** [comment]
Use the `createContext` property in `createTRPCHandle`. Whatever you return from your `createContext` function will be available throughout your resolvers.

1. Define your `createContext`.
> The createContext-function is called for each incoming request so here you can add contextual information about the calling user from the request object. From [trpc docs](https://trpc.io/docs/authorization).

```ts
const createContext = async (request: Request) => {
  const cookies = parse(request.headers.get('cookie') || '');
  const user = await getUser(cookies.accessToken);
  return { user };
};
```


2. Pass it to `createTRPCHandle`

3. Tell your router about it to get full typechecking. [Example](https://github.com/icflorescu/trpc-sveltekit#how-to-use)

```ts
export const router = trpc
  .router<inferAsyncReturnType<typeof createContext>>() // 👈 generic type here
  // queries and mutations...
  .query('hello', {
    resolve: () => 'world',
  });
```

4. `ctx` will now have `user` info in your [resolvers](https://trpc.io/docs/authorization#option-1-authorize-using-resolver) and [middleware](https://trpc.io/docs/authorization#option-2-authorize-using-middleware).

**Comment by ambiguous48** [comment]
Yeah I remember fumbling around trying to make the types work. If you make this change does the `ctx` type get correctly inferred?

```diff
export const router = trpc
  .router<inferAsyncReturnType<typeof createContext>>()
  // .transformer(trpcTransformer)
- .merge('user:', user)
  .query('hello', {
    resolve: ({ctx}) => {
      console.dir('ctx->', ctx)
      return 'ok'
    }
  })

export type Router = typeof router
```

**Comment by ambiguous48** [comment]
You might need to provide the same generic context argument to your other routers, otherwise they'll end up having different context types, which will net you an `unknown` `ctx` type.

You can create a [helper](https://trpc.io/docs/middlewares#createprotectedrouter-helper) function so you don't have to repeat yourself in each router.

**Comment by omar2205** [comment]
Yeah, I went with the middleware. Now, how can I set a cookie from inside a mutation?

**Comment by itstheandre** [comment]
The solution i found was to add some key to locals (like: has cookies) and defined them in each trpc function and then in the hook just add a check on wether that key exists in the `locals`

Something like this:
```ts
if (response.ok && event.url.toString().includes('trpc') && (event.locals as any).hasCookie ) {
response.headers.set('Set-Cookie', (event.locals as any).hasCookie); 
}

```

not the cleanest solution, but to be honest, i also dont hate it

**Comment by itstheandre** [comment]
> Yeah, I went with the middleware. Now, how can I set a cookie from inside a mutation?

The solution i found was to add some key to locals (like: has cookies) and defined them in each trpc function and then in the hook just add a check on wether that key exists in the `locals`

Something like this:
```ts
if (response.ok && event.url.toString().includes('trpc') && (event.locals as any).hasCookie ) {
response.headers.set('Set-Cookie', (event.locals as any).hasCookie); 
}

```

not the cleanest solution, but to be honest, i also dont hate it

**Comment by omar2205** [comment]
@itstheandre can you share how you got access to locals inside trpc functions?
