### ISSUE TITLE
[Feature request] Support for tRPC v11

### ISSUE THREAD

**Issue by KATT** [icflorescu/trpc-sveltekit#101]
We're releasing a new major of tRPC! 🚀 

It looks like you're not importing anything that should break stuff, but would be nice to add `|| ^11.0.0-next-alpha.175` as peer dependency and see if it works

https://trpc.io/docs/v11/migrate-from-v10-to-v11

---

If there's issues when you just bump your deps to `@next`, please open an issue on the tRPC repo! 🙏

**Comment by icflorescu** [comment]
Thanks for the PR!

**Comment by jonathanwilke** [comment]
Is there a stable version of support for trpc 11 coming?
