### ISSUE TITLE
Will this work with trpc11 ?

### ISSUE THREAD

**Issue by alanxp** [icflorescu/trpc-sveltekit#114]
Just as the title, will this be working with the new trpc 11 or is the proyect still alive? I use it in my other projects with trpc 10

**Comment by icflorescu** [comment]
It already works with tRPC 11 beta.
This is not a but. it's a question.

**Comment by wassafr** [comment]
Really ?
With trpc 11 beta I get the following error : 

`SyntaxError: The requested module '@trpc/server/http' does not provide an export named 'resolveHTTPResponse'`

**Comment by ogrotten** [comment]
I just received this as well after following [getting started](https://icflorescu.github.io/trpc-sveltekit/getting-started).

    file:///home/redacted/my%20projects/pm/node_modules/.pnpm/trpc-sveltekit@3.6.3_@sveltejs+adapter-node@5.2.13_@sveltejs+kit@2.22.2_@sveltejs+vite-_92a1568b41e69918f98dfcb76e07126f/node_modules/trpc-sveltekit/dist/server.js:1
    import { resolveHTTPResponse } from '@trpc/server/http';
             ^^^^^^^^^^^^^^^^^^^
    SyntaxError: The requested module '@trpc/server/http' does not provide an export named 'resolveHTTPResponse'

It works after downgrading 

	- @trpc/client 11.4.3
	+ @trpc/client 10.45.2 (11.4.3 is available)
	- @trpc/server 11.4.3
	+ @trpc/server 10.45.2 (11.4.3 is available)
