### ISSUE TITLE
`transformer` no longer works client-side

### ISSUE THREAD

**Issue by BearToCode** [icflorescu/trpc-sveltekit#116]
**Describe the bug**
After updating to latest version, `transformer` no longer works client-side, causing everything to break. I'm pretty sure this is related to #101 . I understand wanting to support the latest version(which is also just in preview using `next`), but this just broke basically all apps using `v10`!

**Comment by icflorescu** [comment]
You are right, of course, sorry for the inconvenience.
Just released `v3.6.0`, that works with tRPC `v10`, and `v4.0.0-next.1` that works with tRPC `next`.
