### ISSUE TITLE
Wrong type of `fetch`

### ISSUE THREAD

**Issue by sproott** [icflorescu/trpc-sveltekit#18]
I tried to follow the docs to get tRPC to work in SSR. I got a type error though.

The fetch function passed to SvelteKit's `load` has a signature like this: `(info: RequestInfo, init?: RequestInit): Promise<Response>`, but Node's `fetch` function's first argument has a broader type: `RequestInfo | URL`. That gives a type mismatch when passing the fetch function to the custom `trpcClient` function:

![image](https://user-images.githubusercontent.com/46423131/179087356-727638c6-b618-48f0-b3e0-b26fa4a40ab6.png)

I had to do a typecast in the `trpcClient` function to get the types to match:

![image](https://user-images.githubusercontent.com/46423131/179087585-c9ca0fa7-4772-4d18-b76f-9d8847f7fb6a.png)

Any idea why the types are different? Perhaps something changed in a newer version of SvelteKit?

**Comment by ambiguous48** [comment]
You can set the signature of your function to explicitly expect sveltekit's fetch. As it currently stands, you're using the global `fetch` type.

Try this instead:
```ts
import type { LoadEvent } from '@sveltejs/kit';

export const trpc = (loadFetch?: LoadEvent['fetch']) => {
  return createTRPCClient<AppRouter>({
      url: loadFetch ? '/trpc' : url,
      ...(loadFetch && { fetch: loadFetch }),
  });
};
```

**Comment by sproott** [comment]
I've done basically that in the bottom picture, but there still needs to be the `as typeof fetch` typecast when passing it to createTRPCClient. My point was that this isn't documented, so the docs probably should be updated to account for this.
