### ISSUE TITLE
Some outdated info

### ISSUE THREAD

**Issue by beeb** [icflorescu/trpc-sveltekit#30]
Let me preface this by saying that I have never used tRPC before and I hope none of this comes from my incompetence. I was really happy to find some resources on using tRPC with sveltekit, although it's a bit of a bumpy ride for now.

**Describe the bug**
The Readme contains some information that is outdated or more generally doesn't reflect best practices as indicated by tRPC and sveltekit.

**To Reproduce**
Try to use the instructions in a fresh sveltekit project

**Expected behavior**
No warnings should appear

**Additional context**
First off, trpc has released or is close to release their v10 apparently, and I had to use v9 instead.

When using the provided code for the trpcServer, the following warning appears:
![image](https://user-images.githubusercontent.com/703631/200667660-e7451885-a295-46b4-8ab5-675c441b3fc6.png)

It seems the [recommended approach](https://trpc.io/docs/v10/quickstart) uses `initTRPC` to construct the router.

Likewise, when creating the client, the recommended approach uses `createTRPCProxyClient` and `httpBatchLink`.

In the Readme, the method recommended to use trpc in the load function for SSR uses the outdated `$app/env` import and doesn't take into account that the dev port is not fixed anymore. Also, the example doesn't show how to use this with `createTRPCProxyClient`.

For the inference helpers, [the tRPC docs](https://trpc.io/docs/v10/infer-types#inference-helpers) also show another method using `inferRouterInputs`.

I would love a revamp of the Readme that takes into account the latest changes of sveltekit and tRPC. Thanks!

**Comment by beeb** [comment]
When this is clarified, I also am experience an error when trying to implement the changes mentioned above:

```
TypeError: e.resolveHTTPResponse is not a function
    at /.../node_modules/.pnpm/trpc-sveltekit@2.3.7_@trpc+server@10.0.0-rc.7/rpc-sveltekit/dist/index.cjs:1:459
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handle (/.../apps/extranet/src/hooks.server.ts:6:18)
    at async respond (file:///.../node_modules/.pnpm/@sveltejs+kit@1.0.0-next.2.0+vite@3.2.3/node_modules/@sveltejs/kit/src/runtime/server/index.js:294:20)
    at async file:///.../node_modules/.pnpm/@sveltejs+kit@1.0.0-next.539_svelte@3.52.0+vite@3.2.3/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:413:22
```

**Comment by vishalbalaji** [comment]
There is a [PR](https://github.com/icflorescu/trpc-sveltekit/pull/29) currently open to migrate to tRPC 10 that has not been merged yet.

**Comment by icflorescu** [comment]
Apologies for being inactive here over the last week.
There are currently many changes breaking changes in both SvelteKit and tRPC.
A full rewrite is in order, of course, and I'll get to it as soon as things get a bit more stable and I find the necessary time.

**Comment by icflorescu** [comment]
tRPC-SvelteKit `v3.x.x` is compatible with tRPC `v10`.
It comes with a few potentially breaking changes, so make sure to go through the documentation website now available at [icflorescu.github.io/trpc-sveltekit](https://icflorescu.github.io/trpc-sveltekit).
