### ISSUE TITLE
Update to tRPC v10

### ISSUE THREAD

**Issue by doceazedo** [icflorescu/trpc-sveltekit#33]
Any plans to update this adapter to use tRPC v10?

- Announcement post: https://trpc.io/blog/announcing-trpc-10
- Migration guide: https://trpc.io/docs/migrate-from-v9-to-v10

**Comment by doceazedo** [comment]
I started migrating it [here](https://github.com/doceazedo/trpc-sveltekit/tree/migrate-trpc-v10) based on [trpc-nuxt](https://github.com/wobsoriano/trpc-nuxt). If that's ok, I can also update the README and open a PR.

**Comment by icflorescu** [comment]
Already working on a rewrite, which also includes a docs website. Will come up with something over the weekend.
