### ISSUE TITLE
How to use createTRPCHandle with custom / local handle logic?

### ISSUE THREAD

**Issue by caschbre** [icflorescu/trpc-sveltekit#46]
The examples have createTRPCHandle completely taking over the svelte server handle hook.  How would we got about mixing our own custom logic in the handle hook?  I believe in 2.x we would do something similar to what's described in this [pull request](https://github.com/icflorescu/trpc-sveltekit/pull/8).  I realize quite a bit has been refactored with the latest 3.x version and that example doesn't work anymore, so looking for an alternative / updated approach?

**Comment by icflorescu** [comment]
Have a look at the [sequence helper function](https://kit.svelte.dev/docs/modules#sveltejs-kit-hooks-sequence) in the SvelteKit docs.
Maybe I should put the link in our docs as well.

**Comment by icflorescu** [comment]
Using the new SvelteKit `sequence` helper is a lot cleaner than our previous approach in `2.x`, IMO.
Please feel free to comment/reopen if this doesn't answer your question.

**Comment by caschbre** [comment]
Thanks! Yeah, a simple note in the docs would be perfect.

**Comment by icflorescu** [comment]
Added, thanks.

**Comment by mileung** [comment]
The sequence link mentioned above is stale.

Here's the new url for the sequence helper function if anyone else is looking for it:

https://svelte.dev/docs/kit/@sveltejs-kit-hooks#sequence
