### ISSUE TITLE
Support for adapter-static

### ISSUE THREAD

**Issue by JitPackJoyride** [icflorescu/trpc-sveltekit#51]
I'm a bit new to trpc, so I am unaware if there is any technical limitations preventing this library from supporting `adapter-static`. But from my understanding, there shouldn't be any such limitation.

If it is tehcnically possible, is there a roadmap for when `adapter-static` would be supported? 

Building desktop apps with Sveltekit necessitates that we use `adapter-static`, for example with Tauri.

**Comment by icflorescu** [comment]
Hey, Ajit!

Asa far as I can tell, there's nothing preventing you from using `trpc-sveltekit` with `adapter-static` - with the single mention that SSR doesn't make sense in this scenario, but I assume you already know this...

**Comment by icflorescu** [comment]
In fact, I'd be really grateful if you test it in your scenario and let me know how things work, so I can update the documentation accordingly.
I think it would benefit other users as well.

I'll leave this issue open for now, for further reference.

**Comment by JitPackJoyride** [comment]
I'd love to contribute and state how my experience is. At the moment, a quick starter project is working as intended.

As you don't seem to be aware of any reason why this won't work, I'm going to continue to build this new app using `adapter-static`. I'll flag issues and hopefully raise some PRs if there are issues for whatever reason.

**Comment by icflorescu** [comment]
I am going to close this for now.
Please feel free to reopen or open a new one if necessary!
