### ISSUE TITLE
My tRPC runs on a different server/port

### ISSUE THREAD

**Issue by muuvmuuv** [icflorescu/trpc-sveltekit#52]
**Describe the bug**

It is not possible to allow specifying that tRPC runs on a different server/origin/port.

**To Reproduce**

**Expected behavior**

Define origin/host by myself if wanted.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by icflorescu** [comment]
I think using `trpc-sveltekit` doesn't make much sense in this case.
Perhaps you should simply use the [trpc vanilla client](https://trpc.io/docs/vanilla).
