### ISSUE TITLE
invalid -> fail

### ISSUE THREAD

**Issue by BCsabaEngine** [icflorescu/trpc-sveltekit#58]
**Describe the bug**
SvelteKit form action invalid response changed to fail.

**To Reproduce**
Just try to run the bokstall example and login with invalid user.

**Expected behavior**
Descibe the form action faulty.

Replace https://github.com/icflorescu/trpc-sveltekit/blob/main/examples/bookstall/src/routes/login/%2Bpage.server.ts#L3 and https://github.com/icflorescu/trpc-sveltekit/blob/main/examples/bookstall/src/routes/login/%2Bpage.server.ts#L29 "invalid" -> "fail"

**Comment by icflorescu** [comment]
Well spotted @BCsabaEngine, thanks!
