### ISSUE TITLE
How to use this package with a separate backend

### ISSUE THREAD

**Issue by yourGuy** [icflorescu/trpc-sveltekit#63]
createTRPCClient only allows relative urls, so how can this package be used with a backend on a separate domain or port ?

**Comment by Sazzo** [comment]
According to https://github.com/icflorescu/trpc-sveltekit/issues/52#issuecomment-1407628849, it's not the use case meant for this library. You should just use the tRPC vanilla client.
https://trpc.io/docs/vanilla

**Comment by icflorescu** [comment]
As @Sazzo says, if your back-end is on a separate domain/port, a  should probably be using the tRPC vanilla client.
tRPC-SvelteKit is suited for monolithic SvelteKit apps.

**Comment by alanxp** [comment]
I need it 

> As @Sazzo says, if your back-end is on a separate domain/port, a should probably be using the tRPC vanilla client. tRPC-SvelteKit is suited for monolithic SvelteKit apps.

I need it to work in both scenarios, one scenario is as a sveltekit app (monolithic) and therefore the url is local, and the other scenario is when it's running not at theserver.com, lets say it will run as an app through "webview", so i would like to point the URL to the sveltekit monolithic app. 

and that way, both ways are covered.
