### ISSUE TITLE
How can I update all clients automatically on data changes in db?

### ISSUE THREAD

**Issue by ErcouldnT** [icflorescu/trpc-sveltekit#66]
I'm working on "😎 tRPC-SvelteKit example: Bookstall" and I'd like to see all connected clients' data have updated automatically in UI whenever a data changes in db like deleting a content.

Is that not possible with tRPC?

**Comment by icflorescu** [comment]
I assume you're aware that realtime behaviour requires websockets, regardless of whether you're using [tRPC.io](https://trpc.io/) with React or this package with SvelteKit.
SvelteKit doesn't have yet native support for websockets, but we have an active PR for a (temporary) workaround in `trpc-sveltekit`. I'll hopefully find the necessary time to test and pull it within the next couple of days.

**Comment by SrZorro** [comment]
Hi @ErcouldnT 

> is it not possible to do that with vercel or netlify adapter?

If they give support for websockets there is a way to create a workaround to make tRPC with sveltekit work with them, but I do not use vercel nor netlify so I cannot provide a workaround for them.

> And also I need a "Hello World" example for web-socket subscription. Unfortunately I couldn't do it...

You are right, the [example router](https://github.com/icflorescu/trpc-sveltekit/blob/main/examples/websocket/src/lib/trpc/router.ts) does not show how to do a subscription with tRPC, I will try this week to update the example with a subscription.
