### ISSUE TITLE
Getting `TypeError: rt.transformer.serialize is not a function`

### ISSUE THREAD

**Issue by SorenHolstHansen** [icflorescu/trpc-sveltekit#72]
**Describe the bug**
I am trying to migrate my project to turborepo. Everything worked fine in dev, but when i build and run `npm run preview` I get 
```
/Users/.../node_modules/@trpc/client/dist/httpRequest-66400297.cjs.prod.js:73
    return rt.transformer.serialize(_input);
                          ^

TypeError: rt.transformer.serialize is not a function
    at /Users/.../node_modules/@trpc/client/dist/httpRequest-66400297.cjs.prod.js:73:27
    at Array.map (<anonymous>)
    at Object.httpRequest (/Users/.../node_modules/@trpc/client/dist/httpRequest-66400297.cjs.prod.js:72:99)
    at /Users/.../node_modules/@trpc/client/links/httpBatchLink/dist/trpc-client-links-httpBatchLink.cjs.prod.js:138:40
    at Timeout.dispatch (/Users/.../node_modules/@trpc/client/links/httpBatchLink/dist/trpc-client-links-httpBatchLink.cjs.prod.js:36:22)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```
I am still on version 2.3.6 and trpc 9.27.2 if that is causing the issues. Also don't know if this is a trpc-sveltekit problem or a trpc problem.

**To Reproduce**
1. Start a turborepo repo
2. Setup trpc-sveltekit with the instructions for v2
3. run npm run build
4. run npm run preview
5. Get the above error

**Expected behavior**
I expected the preview to work as in dev

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: firefox
 - Version: 109

**Comment by icflorescu** [comment]
Not a `trpc-sveltekit` problem, actually.
I believe your repo makes use of a `trpc-transformer` convenience package that I've built a while ago, and the error most likely comes from [an older issue in that package](https://github.com/icflorescu/trpc-transformer/issues/2) which should now be fixed.
Bottom line: upgrade `trpc-transformer` to the latest version and the error should go away.

**Comment by SorenHolstHansen** [comment]
Thanks a lot, that fixed it!
