### ISSUE TITLE
Resolving conflict with trpc-sveltekit and [...rest] directory on the root route

### ISSUE THREAD

**Issue by amit13k** [icflorescu/trpc-sveltekit#79]
I'm fairly new to SvelteKit, and I'm using trpc-sveltekit in my project. I've encountered a problem when trying to use a [...rest] directory on the root route. According to the [documentation](https://icflorescu.github.io/trpc-sveltekit/recipes-and-caveats), trpc-sveltekit reserves the /trpc path prefix, which seems to conflict with the [...rest] directory. 

As a result, I am getting an error like "No \"query\"-procedure on path" when using trpc-sveltekit alongside the [...rest] directory on the root route. I have tried matchers like [...rest=exclude_trpc] where exclude_trpc is a regex that matches everything except /trpc* but they don't seem to work. Any suggestions for how to resolve this issue?

**Comment by multiplehats** [comment]
Perhaps you could setup your own endpoint?

I wrote a lil guide: https://github.com/icflorescu/trpc-sveltekit/discussions/87
