### ISSUE TITLE
preview command triggers `createTRPCWebSocketServer` error

### ISSUE THREAD

**Issue by llmaboi** [icflorescu/trpc-sveltekit#82]
**Describe the bug**
Using the example found on the websocket: https://github.com/icflorescu/trpc-sveltekit/tree/main/examples/websocket

Following the above will result in an error showing in the console about
```bash
> example-websocket@0.0.0 preview
> vite preview --port 3003


WebSocket server not found but 'createTRPCWebSocketServer' had been called
```

**To Reproduce**
1. Initializing package, 
2. Installing packages, 
3. Running `npm run build`
4. Running `npm run preview`.
5. See the error

**Expected behavior**
Preview of the built application can be run, whether that us using the `npm start` && `npm run preview` command or some other combination.

**Desktop (please complete the following information):**
 - OS: Windows -> WSL
 - Browser -- N/A
 - Version -- N/A

**Comment by icflorescu** [comment]
The WSS support developed by [SrZorro](https://github.com/SrZorro) is experimental and only works with a Node.js server.
So you should simply run `npm start`.
I've deleted the `preview` script to avoid confusion.
