### ISSUE TITLE
Setting cookies in trpc router doesn't work

### ISSUE THREAD

**Issue by mKepka16** [icflorescu/trpc-sveltekit#93]
Describe the bug
The bug is related to setting cookies in the trpc router. Despite writing code to set cookies in the response, the cookies are not being set in the client browser, and there is no "set-cookie" header in the response.

To Reproduce

Go to the specified route 'login'.
Provide the required input data, including a valid login and password.
Trigger the login process.
Expected behavior
After successful login, the server should set a cookie named 'cookie1' with the value 'value1' in the client browser. The response from the server should include the "set-cookie" header.

Additional context
The following code represents the 'login' route in the trpc router, which should set the cookie:
`router
  .login
    .mutation(async ({ input, ctx }) => {
      const login = input.login;
      const user = await db.user.findFirst({ where: { login } });
      if (!user) return 'bad login';

      const isPasswordValid = await AuthUtils.validatePassword(
        input.password,
        user.password,
        user.salt
      );

      if (!isPasswordValid) return 'wrong password';

      ctx.cookies.set('cookie1', 'value1', { secure: false, httpOnly: false, path: '/' });
      console.log('cookie set');

      return user;
    });
`

Additionally, the context file 'createContext' is provided below:
`export async function createContext(event: RequestEvent) {
  try {
    const token = event.cookies.get('jwt');
    // 👆 or, if we're using HTTP headers based authentication, we could do something like this:
    // const token = event.request.headers.get('authorization')?.replace('Bearer ', '');

    const { id: userId } = jwt.verify(token || '', JWT_SECRET) as {
      id: string;
    };

    return { ...event, userId };
  } catch {
    return { ...event, userId: '' };
  }
}
`

The issue occurs when trying to set the 'cookie1' cookie inside the 'login' route using ctx.cookies.set(...). Although the console.log('cookie set') statement executes correctly, the cookie is not being set in the client browser, and the response header is missing the "set-cookie" field.

Any assistance in resolving this issue would be greatly appreciated. Thank you!

**Comment by ptrxyz** [comment]
I think this error can be generalized to all headers. `event.setHeader` also does not seem to work.

Just curious, @icflorescu seems to be assigned to this, can you maybe shed some light into this? did you already have the chance to look into this bug and maybe have an outline what goes wrong?

**Comment by ralphwest1** [comment]
I'm running into this issue as well. Any update or path to resolution?

**Comment by ptrxyz** [comment]
> I'm running into this issue as well. Any update or path to resolution?

There was no sign of activity on here, so I moved on to this alternative: https://shtz.sveltering.com/docs/v0/setting-up
It works flawlessly.

Demo here: https://www.youtube.com/watch?v=UHxqGq0AX3c and https://www.youtube.com/watch?v=OyzI21V3d14

**Comment by ralphwest1** [comment]
> There was no sign of activity on here, so I moved on to this alternative: https://shtz.sveltering.com/docs/v0/setting-up It works flawlessly.
> Demo here: https://www.youtube.com/watch?v=UHxqGq0AX3c and https://www.youtube.com/watch?v=OyzI21V3d14

@ptrxyz Thank you, very helpful!
